mode: learning
media_root: media
media_url: /media
base_url: /
# If your site is nested inside of a bigger one, you can use media_url and
# base_url to properly generate links on your site. For example, if your URL
# will be some.domain.com/starter/, use:
#   media_url: /starter/media
#   base_url: /starter/
template: hyde.ext.templates.jinja.Jinja2Template
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.meta.AutoExtendPlugin
    # Plugins needed for the advances section.
context:
    data:
        author:
            name: Etienne Batise
            url: "http://etienne.batise.fr"
        layout:
            name: etiennebatiselayout
            url: "https://github.com/merlinrebrovic/hyde-starter-kit"
        project:
            name: My Website
            url: "http://hyde.github.com"
            install: "https://github.com/hyde/hyde#installation"
        # menu:
        #   - title: Home
        #     url: index.html
        #   - title: First steps
        #     url: first-steps.html
        #   - title: About
        #     url: about.html

### Advanced part ###

# This defines meta data on the whole site.
meta:
    # 'nodemeta' will tell Hyde what file to look for inside a folder from
    # which to apply meta data to all files (resources) inside it. This is
    # a great way of simply adding or modifying properties of a very large
    # number of files.
    nodemeta: meta.yaml
    ga_tracking_code: XX-XXXXXXXX-X

